### ISSUE TITLE
Calling dispose() after shutdown() on Kernel throws an exception

### ISSUE THREAD

**Issue by doronrosenberg** [jupyter/jupyter-js-services#70]
I am trying to shutdown a Kernel but am seeing "Connection lost, reconnecting in X seconds." messages after that.  So I tried to call a dispose() on the Kernel object and get:

```
/Users/doronrosenberg/mystuff/ibm/eclairjs/git/eclairjs-node/node_modules/jupyter-js-services/lib/kernel.js:762
            var future = this._futures.get(parentHeader.msg_id);
                                      ^

TypeError: Cannot read property 'get' of null
    at Kernel._onWSMessage (/Users/doronrosenberg/mystuff/ibm/eclairjs/git/eclairjs-node/node_modules/jupyter-js-services/lib/kernel.js:762:39)
    at WebSocket._ws.onmessage (/Users/doronrosenberg/mystuff/ibm/eclairjs/git/eclairjs-node/node_modules/jupyter-js-services/lib/kernel.js:734:53)
    at WebSocket.onMessage (/Users/doronrosenberg/mystuff/ibm/eclairjs/git/eclairjs-node/node_modules/ws/lib/WebSocket.js:418:14)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (/Users/doronrosenberg/mystuff/ibm/eclairjs/git/eclairjs-node/node_modules/ws/lib/WebSocket.js:816:10)
    at /Users/doronrosenberg/mystuff/ibm/eclairjs/git/eclairjs-node/node_modules/ws/lib/Receiver.js:477:18
    at Receiver.applyExtensions (/Users/doronrosenberg/mystuff/ibm/eclairjs/git/eclairjs-node/node_modules/ws/lib/Receiver.js:364:5)
    at /Users/doronrosenberg/mystuff/ibm/eclairjs/git/eclairjs-node/node_modules/ws/lib/Receiver.js:466:14
    at Receiver.flush (/Users/doronrosenberg/mystuff/ibm/eclairjs/git/eclairjs-node/node_modules/ws/lib/Receiver.js:340:3)
```

https://github.com/jupyter/jupyter-js-services/blob/master/src/kernel.ts#L776 needs a null check, but I also wondering how do I correctly shutdown the connection to a Kernel if shutdown() doesn't do it (as it keeps trying to reconnect)?

Using 0.3.3 and Node.js (using the ws package version 1.0.1 for websockets).

**Comment by blink1073** [comment]
Yep, agreed on the `null` check.  Perhaps this promise isn't being fulfilled, and we should take the action on reject as well:  https://github.com/jupyter/jupyter-js-services/blob/master/src/kernel.ts#L533.

**Comment by doronrosenberg** [comment]
@blink1073 From debugging that promise resolves successfully. ```_status``` is being set to ```6```, but by the time we get ```_onWSClose()```, ```status``` is back to ```4```.

Between ```shutdown()``` and ```_onWSClose()```, ```_onWSMessage``` is being called with ```4```.

Not sure if the code could close the websocket earlier perhaps, I assume the ```onWSMessage``` call is a result of the ajaxRequest to shutdown the kernel.  The other choice would be to have ```_updateStatus``` check if the current status is ```Dead``` and if so not update the status to the new status (not sure if that is correct, can a Dead kernel be brought back up via a restart?).

**Comment by blink1073** [comment]
Yes, a `Dead` kernel can be restarted manually.  You mean that `_onWSMessage` is getting called between the call to `this._ws.close()` and `_onWSClose()`?  If so, we could set a separate flag to indicate we are manually closing, and ignore any incoming messages if that flag is set.
